---
title: "996 Analysis"
author: "Zheng Zhang, "
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
```


# I - Introduction



# II - Data Preprocessing

### Load datasets

```{r}
dt_issues = read.csv("data/issues_data.csv", header=TRUE)
dt_star = read.csv("data/stargazers.csv", header=TRUE)
dt_user = read.csv("data/users_data.csv", header=TRUE)
```

### Saniety Check

```{r}
# Inspect the dataset by taking the first 10 rows of each dataset. 
dt_issues %>% head(10)
dt_star %>% head(10)
dt_user %>% head(10)
```

### Data Cleaning

```{r}
# User dataset cleaning
# Cleaning
dt_user_cld <- dt_user %>% 
    # Drop unused features. 
    select(-X_id, -avatar_url, -events_url, -followers_url, -following_url, 
           -gists_url, -gravatar_id, -html_url, -node_id, -public_gists, -received_events_url, 
           -repos_url, -site_admin, -starred_url, -subscriptions_url, -type) %>%
    # Convert the time/date features to relative format. 
    mutate(created_at = lubridate::ymd_hms(created_at), 
           updated_at = lubridate::ymd_hms(updated_at)) %>%
    # Convert various factor type features to string type. 
    mutate(bio = as.character(bio), 
           blog = as.character(blog), 
           company = as.character(company), 
           email = as.character(email), 
           location = as.character(location), 
           login = as.character(login), 
           name = as.character(name), 
           organizations_url = as.character(organizations_url),
           url = as.character(url))

str(dt_user_cld)
```

# III - Data Analysis

## 1. What Companies are those programmers in?

```{r}
company_info <- dt_user_cld %>% 
    group_by(company) %>%
    summarise(count = n()) %>%
    arrange(desc(count)) %>%
    filter(company != "")

# Display the top companies. 
company_info

# Display the company list.
print(company_info$company)
```


```{r}
# Define the company aggregation function. 
company_aggregation <- function(name) {
    # Make case insensitive. 
    name <- toupper(name)
    # Detect pattern and change the company name accordingly. 
    if (grepl("百度|BAIDU|AIDU", name)) {
        target_name <- "Baidu"
    } else if (grepl("ENCENT", "腾讯", "TENCENT", name)) {
        target_name <- "Tencent"
    } else if (grepl("LIBABA|淘宝|AOBAO|LIPAY|阿里巴巴|LIYUN|阿里云", name)) {
        target_name <- "Alibaba"
    } else if (grepl("JD|京东", name)) {
        target_name <- "JD"
    } else if (grepl("ETEASE|网易", name)) {
        target_name <- "NetEase"
    } else if (grepl("EITUAN|美团", name)) {
        target_name <- "MeiTuan"
    } else if (grepl("YTEDANCE|字节|头条", name)) {
        target_name <- "ByteDance"
    } else if (grepl("ELEME|饿了", name)) {
        target_name <- "Eleme"
    } else if (grepl("UAWEI|华为", name)) {
        target_name <- "Huawei"
    } else if (grepl("DIDI|滴滴|嘀嘀", name)) {
        target_name <- "DiDi"
    } else {
        target_name <- name
    }
    
    return (target_name)
}

# Aggregating disparse companies. 
company_info_agg <- company_info %>% 
    mutate(company_agg = company_aggregation(company))
    
```


































